import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
		<div className="md:min-h-screen w-screen bg-home py-36 flex flex-col justify-ceter">
			<Head>
				<title>Welcome | Siliragung</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className=" w-full h-full m-auto flex justify-center items-center flex-col text-white space-y-24">
				<div>
					<h3 className="text-xl">Welcome to</h3>
					<h1 className=" text-5xl md:text-9xl dm-serif">Siliragung</h1>
				</div>
			</div>
				<div className="animate-bounce text-white flex justify-center">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						className="h-6 w-6"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
					>
						<path
							strokeLinecap="round"
							strokeLinejoin="round"
							strokeWidth="2"
							d="M19 14l-7 7m0 0l-7-7m7 7V3"
						/>
					</svg>
				</div>
		</div>
	);
}
