name: Run Lighthouse CI
on: [pull_request]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Waiting Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
        id: siliragung
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 100
      
      - name: Preview URL
        run: echo ${{ steps.siliragung.outputs.url }}

      - name: Run Lighthouse
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci collect --url=${{ steps.siliragung.outputs.url }} --url=${{ steps.siliragung.outputs.url }}/contents --url=${{ steps.siliragung.outputs.url }}/about
          echo "\n"
          lhci upload --target "temporary-public-storage" --githubAppToken "$LHCI_GITHUB_APP_TOKEN" --githubToken "$GITHUB_TOKEN"
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
